services:
  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.6.2
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"

      KAFKA_REST_SCHEMA_REGISTRY_URL: https://psrc-xxxxx.yyyyyyy.zzz.confluent.cloud
      KAFKA_REST_CLIENT_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
      KAFKA_REST_CLIENT_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: <SR_API_KEY>:<SECRET>

      KAFKA_REST_BOOTSTRAP_SERVERS: pkc-xxxx.yyyyyyy.zzz.confluent.cloud:9092
      
      KAFKA_REST_CLIENT_SSL_ENDPOINT_IDENTIFIED_ALGORITHM: https
      KAFKA_REST_CLIENT_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_REST_CLIENT_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required \
                                   username="<KAFKA_API_KEY>" \
                                   password="<SECRET>";
      KAFKA_REST_CLIENT_SASL_MECHANISM: PLAIN
      KAFKA_REST_LOG4J_ROOT_LOGLEVEL: DEBUG

