services:
  kafka:
    image: confluentinc/confluent-local:7.6.2
    hostname: kafka
    container_name: kafka-rp
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT  
      KAFKA_LISTENERS: BROKER://:9092,PLAINTEXT_HOST://:29092, CONTROLLER://:29093  
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka:9092,PLAINTEXT_HOST://localhost:29092  
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER  
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER

  sr:
    image: confluentinc/cp-schema-registry:7.6.2
    hostname: sr
    container_name: sr-rp
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: sr
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  rp:
    image: confluentinc/cp-kafka-rest:7.6.2
    hostname: rp
    container_name: rp-rp
    depends_on:
      - kafka
      - sr
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: rp-rp
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://sr:8081
      KAFKA_REST_AUTO_REGISTER_SCHEMAS: false
      KAFKA_REST_CONSUMER_MAX_POLL_RECORDS: 100
      KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 30000